package com.example.greatweek.app

object Constants {
    const val KEY_ADD_ROLE_REQUEST_KEY = "KEY_ADD_ROLE_REQUEST_KEY"
    const val KEY_RENAME_ROLE_REQUEST_KEY = "KEY_RENAME_ROLE_REQUEST_KEY"

    const val KEY_ADD_GOAL_FOR_A_ROLE_REQUEST_KEY = "KEY_ADD_GOAL_FOR_A_ROLE_REQUEST_KEY"
    const val KEY_ADD_GOAL_FOR_A_DAY_REQUEST_KEY = "KEY_ADD_GOAL_FOR_A_DAY_REQUEST_KEY"
    const val KEY_EDIT_GOAL_REQUEST_KEY = "KEY_EDIT_GOAL_REQUEST_KEY"
}