package com.example.greatweek.app.presentation.constants

const val KEY_ADD_ROLE_REQUEST_KEY = "KEY_ADD_ROLE_REQUEST_KEY"
const val KEY_RENAME_ROLE_REQUEST_KEY = "KEY_RENAME_ROLE_REQUEST_KEY"

const val KEY_ADD_GOAL_FOR_A_ROLE_REQUEST_KEY = "KEY_ADD_GOAL_FOR_A_ROLE_REQUEST_KEY"
const val KEY_ADD_GOAL_FOR_A_DAY_REQUEST_KEY = "KEY_ADD_GOAL_FOR_A_DAY_REQUEST_KEY"
const val KEY_EDIT_GOAL_REQUEST_KEY = "KEY_EDIT_GOAL_REQUEST_KEY"

const val SCROLL_DELAY_MS = 500L
const val DRAG_STATE_RIGHT = 1
const val DRAG_STATE_LEFT = -1
const val DRAG_STATE_IDLE = 0